title: Living The Blue Book
subtitle: Laughing everlastingly
description: A blaze of light in every word
author: cryptowanderer
timezone: UTC

language: [en]
locale: en
i18n:
  type: [page, post]
permalink_defaults:
  lang: en
i18n_dir: :lang

url: https://living.thebluebook.co.za
root: /
permalink: news/:year/:month/:day/:title/
archive_dir: news
code_dir: downloads/code
new_post_name: :year-:month-:day-:title.md # File name of new posts
post_asset_folder: true
per_page: 0

highlight:
  enable: false

theme: navy
deploy:
  type: git
  repo: git@github.com:andytudhope/living-blue-book.git
  branch: gh-pages

twitter: cryptowanderer
github: andytudhope
